### ISSUE TITLE
After asking for room id, it errors

### ISSUE THREAD

**Issue by RikerW** [The-Quill/SE-Chat-Terminal#11]
Full text:

```
MacBook-Pro:SE-Chat-Terminal-master rikerw$ node start.js
Command name (do /help for a list of commands):  /join
Chat Domain (abbreviated):  Unhandled rejection There was an issue with the response. Check your config is correct.

Unhandled rejection There was an issue with the response. Check your config is correct.

Unhandled rejection There was an issue with the response. Check your config is correct.

SE
room id:  240
readline.js:925
            throw err;
            ^

TypeError: core.chatAbbreviationToFull is not a function
    at /Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/prompt.js:82:35
    at /Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/node_modules/prompt/lib/prompt.js:336:32
    at /Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/node_modules/prompt/lib/prompt.js:333:9)
    at /Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/node_modules/prompt/lib/prompt.js:342:32
    at /Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/Users/WachtlerMacBook/Downloads/SE-Chat-Terminal-master/node_modules/read/lib/read.js:111:5)
    at emitOne (events.js:90:13)
    at Interface.emit (events.js:182:7)
    at Interface._onLine (readline.js:211:10)
    at Interface._line (readline.js:550:8)
    at Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKeys (readline.js:1251:14)
MacBook-Pro:SE-Chat-Terminal-master rikerw$ 
```

**Comment by RikerW** [comment]
It seems to connect fine if I run `node start.js`, and spits out random messages. But typing /join, then SE, then 240 gives me errors.

**Comment by vihanb** [comment]
did you run `npm install` in the directory?

**Comment by RikerW** [comment]
Yes.

**Comment by The-Quill** [comment]
I fixed this at some point, I can't find the commit, so I'll just leave it at that.

**Comment by RikerW** [comment]
Okay.
