### ISSUE TITLE
halp, config.js not working

### ISSUE THREAD

**Issue by vihanb** [The-Quill/SE-Chat-Terminal#23]
How to reproduce (the bug);

 1. Installed .zip from github
 2. `npm install`
 3. `node start`
 4. Get this error:

```
module.js:340
    throw err;
    ^

Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/vihan/Downloads/SE-Chat-Terminal-master/chat_modules/config.js:1:82)
```

I gave the program my password too

**Comment by The-Quill** [comment]
You need to have a config.json file now as per an update, use the config sample as a starting point

**Comment by vihanb** [comment]
I figured that out but now I get: 

```
Error: the loaded config files has incorrectly formatted or missing room domains
```

my config is:

```
{
    "debug": false,
    "star_threshold": 5,
    "StackExchange": {
        "rooms": {
            "240": {
                "name": "The Nineteenth Byte",
                "room_id": 240
            }
        }
    },
    "MetaStackExchange": {
        "rooms": {
        }
    },
    "StackOverflow": {
        "rooms": {
        }
    }
}
```

**Comment by The-Quill** [comment]
@vihanb whoops, I forgot to update the config sample. Fix coming in one sec

**Comment by The-Quill** [comment]
@vihanb see the updated config file
